services:
  game_server_base:
    build:
      context: .
      dockerfile: "./DockerFiles/Dockerfile.game_server"
    image: game_server_base:latest

  mongodb:
    image: mongo:8.0.9
    container_name: hypixel_mongo
    environment:
      MONGO_INITDB_DATABASE: Minestom
    volumes:
      - ./configuration/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - hypixel_network

  redis:
    image: redis:latest
    container_name: hypixel_redis
    ports:
      - "6379:6379"
    networks:
      - hypixel_network

  proxy:
    build:
      context: .
      dockerfile: "./DockerFiles/Dockerfile.proxy"
    container_name: hypixel_proxy
    ports:
      - "25565:25565"
    depends_on:
      - mongodb
      - redis
    networks:
      - hypixel_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "25565"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

# ------- Limbo Server ------
  nanolimbo:
    image: game_server_base:latest
    container_name: nanolimbo
    environment:
      JAR_FILE: "NanoLimbo-1.9.1-all.jar"
    ports:
      - "65535:65535"
    depends_on:
      proxy:
        condition: service_healthy
    networks:
      - hypixel_network


# ----- Services ------
  service_api:
    image: game_server_base:latest
    container_name: service_api
    environment:
      JAR_FILE: "ServiceAPI.jar"
    depends_on:
      proxy:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - hypixel_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  service_auctionhouse:
    image: game_server_base:latest
    container_name: service_auctionhouse
    environment:
      JAR_FILE: "ServiceAuctionHouse.jar"
    depends_on:
      proxy:
        condition: service_healthy
      service_api:
        condition: service_healthy
    networks:
      - hypixel_network

  service_bazaar:
    image: game_server_base:latest
    container_name: service_bazaar
    environment:
      JAR_FILE: "ServiceBazaar.jar"
    depends_on:
      proxy:
        condition: service_healthy
      service_api:
        condition: service_healthy
    networks:
      - hypixel_network

  service_itemtracker:
    image: game_server_base:latest
    container_name: service_itemtracker
    environment:
      JAR_FILE: "ServiceItemTracker.jar"
    depends_on:
      proxy:
        condition: service_healthy
      service_api:
        condition: service_healthy
    networks:
      - hypixel_network


# ----- Game Servers ------
  skyblockcore_island:
    restart: unless-stopped
    image: game_server_base:latest
    container_name: skyblockcore_island
    environment:
      JAR_FILE: "SkyBlockCore.jar"
      ARGS: "ISLAND"
      PREVIEW_FLAG: "--enable-preview"
    ports:
      - "20000:20000"
    depends_on:
      proxy:
        condition: service_healthy
    networks:
      - hypixel_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "20000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  skyblockcore_hub:
    restart: unless-stopped
    image: game_server_base:latest
    container_name: skyblockcore_hub
    environment:
      JAR_FILE: "SkyBlockCore.jar"
      ARGS: "HUB"
      PREVIEW_FLAG: "--enable-preview"
    ports:
      - "20001:20001"
    depends_on:
      proxy:
        condition: service_healthy
      skyblockcore_island:
        condition: service_healthy
    networks:
      - hypixel_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "20001"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  skyblockcore_farming:
    restart: unless-stopped
    image: game_server_base:latest
    container_name: skyblockcore_farming
    environment:
      JAR_FILE: "SkyBlockCore.jar"
      ARGS: "THE_FARMING_ISLANDS"
      PREVIEW_FLAG: "--enable-preview"
    ports:
      - "20002:20002"
    depends_on:
      proxy:
        condition: service_healthy
      skyblockcore_island:
        condition: service_healthy
      skyblockcore_hub:
        condition: service_healthy
    networks:
      - hypixel_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "20002"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


volumes:
  mongodb-data:
    driver: local

networks:
  hypixel_network:
    driver: bridge